<?php
/**
 * Magento
 *
 * @category    design
 * @package     meigeetheme_default
 * @copyright   Copyright (c) 2012 MeigeeTeam. (http://www.meigeeteam.com)
 */
?>
<?php
/**
 * Shopping cart template
 *
 * @see Mage_Checkout_Block_Cart
 */
?>
<?php
    $meigee_harbour_appearance = MAGE::helper('ThemeOptionsHarbour')->getThemeOptionsHarbour('meigee_harbour_appearance');
    $cartpage = $meigee_harbour_appearance['layout']['cartpage'];
    $subtotal = Mage::helper('checkout/cart')->getQuote()->getSubtotal();
?>
<div class="cart cart-2">
    <div class="shipping-mess-m">
        <?php if($subtotal < 35): 
            $shipping_value = 35 - $subtotal;
            $formattedPrice = Mage::helper('core')->currency($shipping_value, true, false);
        ?>
            <p class="shipping-total"><?php echo $this->__("You're only ")?> <span style="color:#8e0000;"><?php echo $formattedPrice; ?></span> <?php echo $this->__(" away from Free Shipping!"); ?></p>
        <?php else: ?>
            <p class="shipping-total"><?php echo $this->__('Congratulations! You qualify for FREE Ground Shipping!'); ?></p>
        <?php endif; ?>
        
    </div>
    <div class="page-title title-buttons">
        <h1><?php echo $this->__('Shopping Cart') ?></h1>
        <?php if(!$this->hasError()): ?>
        <ul class="checkout-types top-checkout">
            <?php foreach ($this->getMethods('top_methods') as $method): ?>
                <?php if ($methodHtml = $this->getMethodHtml($method)): ?>
                    <li><?php echo $methodHtml; ?></li>
                <?php endif; ?>
            <?php endforeach; ?>
        </ul>
        <?php endif; ?>
        <br class="clear" />
    </div>
    <div class="grid_9 alpha">
        <?php echo $this->getMessagesBlock()->toHtml() ?>
        <?php echo $this->getChildHtml('form_before') ?>
        <form action="<?php echo $this->getFormActionUrl() ?>" method="post">
            <?php echo $this->getBlockHtml('formkey'); ?>
            <fieldset>
                <table id="shopping-cart-table" class="data-table cart-table">
                <col />
                <?php if ($this->helper('tax')->displayCartPriceExclTax() || $this->helper('tax')->displayCartBothPrices()): ?>
                    <col width="1" />
                <?php endif; ?>
                <?php if ($this->helper('tax')->displayCartPriceInclTax() || $this->helper('tax')->displayCartBothPrices()): ?>
                    <col width="1" />
                <?php endif; ?>
                    <col width="1" />
                <?php if ($this->helper('tax')->displayCartPriceExclTax() || $this->helper('tax')->displayCartBothPrices()): ?>
                    <col width="1" />
                <?php endif; ?>
                <?php if ($this->helper('tax')->displayCartPriceInclTax() || $this->helper('tax')->displayCartBothPrices()): ?>
                    <col width="1" />
                <?php endif; ?>
                <?php $mergedCells = ($this->helper('tax')->displayCartBothPrices() ? 2 : 1); ?>
                    <thead>
                        <tr>
                            <th rowspan="<?php echo $mergedCells; ?>"><span class="nobr"><?php echo $this->__('Product Name') ?></span></th>
                            <th class="a-center" colspan="<?php echo $mergedCells; ?>"><span class="nobr"><?php echo $this->__('Unit Price') ?></span></th>
                            <th rowspan="<?php echo $mergedCells; ?>" class="a-center"><?php echo $this->__('Qty') ?></th>
                            <th class="a-center" colspan="<?php echo $mergedCells; ?>"><?php echo $this->__('Subtotal') ?></th>
                        </tr>
                        <?php if ($this->helper('tax')->displayCartBothPrices()): ?>
                        <tr>
                            <th class="a-center"><?php echo $this->helper('tax')->getIncExcTaxLabel(false) ?></th>
                            <th><?php echo $this->helper('tax')->getIncExcTaxLabel(true) ?></th>
                            <th class="a-center"><?php echo $this->helper('tax')->getIncExcTaxLabel(false) ?></th>
                            <th><?php echo $this->helper('tax')->getIncExcTaxLabel(true) ?></th>
                        </tr>
                        <?php endif; ?>
                    </thead>
                    <tfoot>
                        <tr class="buttons-row">
                            <td colspan="50" class="a-right buttons">
                                <div>
                                    <?php if($this->getContinueShoppingUrl()): ?>
                                        <button type="button" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Continue Shopping')) ?>" class="button btn-continue" onclick="setLocation('<?php echo Mage::helper('core')->quoteEscape($this->getContinueShoppingUrl()) ?>')"><span><span><?php echo $this->__('Continue Shopping') ?></span></span></button>
                                    <?php endif; ?>
                                    <button type="submit" name="update_cart_action" value="empty_cart" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Clear Shopping Cart')); ?>" class="button btn-clear"><span><span><?php echo $this->__('Clear Shopping Cart'); ?></span></span></button>
                                    <button type="submit" name="update_cart_action" value="update_qty" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Update Shopping Cart')); ?>" class="button btn-update"><span><span><?php echo $this->__('Update Shopping Cart'); ?></span></span></button>
                                </div>
                            </td>
                        </tr>
                    </tfoot>
                    <tbody>
                    <?php foreach($this->getItems() as $_item): ?>
                        <?php echo $this->getItemHtml($_item) ?>
                    <?php endforeach ?>
                    </tbody>
                </table>
                <script type="text/javascript">decorateTable('shopping-cart-table')</script>
            </fieldset>
        </form>
        <div class="shipping-mess">
            <?php 
                if($subtotal < 35): 
                    $shipping_value = 35 - $subtotal;
                    $formattedPrice = Mage::helper('core')->currency($shipping_value, true, false);
                ?>
                    <p class="shipping-total"><span class="messchamthan">!</span><?php echo $this->__(" You're only "). $formattedPrice. $this->__(" away from Free Shipping!"); ?></p>
                <?php else: ?>
                    <p class="shipping-total"><?php echo $this->__('Congratulations! You qualify for FREE Ground Shipping!'); ?></p>
                <?php endif; ?>
            
        </div>
        <div class="clear"></div>
        <?php echo $this->getChildHtml('crosssell_big') ?>

    </div>
    <aside class="grid_3 omega totals-main">
        <section class="totals">
            <!-- <div class="totals"> -->
            <header class="cart-blocks-title">
                <h2><?php echo $this->__('Total') ?></h2>
            </header>
            <div class="totals-border">
                <div class="totals-wrapper"><?php echo $this->getChildHtml('totals'); ?></div>
                <?php if(!$this->hasError()): ?>
                    <ul class="checkout-types">
                        <?php foreach ($this->getMethods('methods') as $method): ?>
                            <?php if ($methodHtml = $this->getMethodHtml($method)): ?>
                                <li><?php echo $methodHtml; ?></li>
                            <?php endif; ?>
                        <?php endforeach; ?>
                    </ul>
                <?php endif; ?>
            </div>
            <!-- </div> -->
        </section>
        <section style="display:none;">
            <?php if (!$this->getIsVirtual()): ?>
                <?php echo $this->getChildHtml('shipping'); ?>
            <?php endif; ?>
        </section>
        <section class="block-colright payment-wrap">
            <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('harbour-payment-block')->toHtml(); ?> 
        </section>
        
        <div class="clear"></div>

        <section class="block-colright needhelp-wrap">
            <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('harbour-needhelp-block')->toHtml(); ?> 
        </section>
    </aside>
    <!-- <aside class="grid_3 omega">
        <section class="block-colright needhelp-wrap">
            <?php //echo $this->getLayout()->createBlock('cms/block')->setBlockId('harbour-needhelp-block')->toHtml(); ?> 
        </section>
    </aside> -->
    <div class="grid_9 alpha congift-wrap">
        <div class="main-cogift">
            <table class="table-cogift">
                <tr>
                    <?php if($this->getChildHtml('coupon')): ?>
                        <section class="coupon">
                            <?php echo $this->getChildHtml('coupon') ?>
                        </section>
                    <?php endif; ?>
                </tr>
                
            </table>    
        </div>
        <div class="needhelp-tablet">
            <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('harbour-needhelp-block')->toHtml(); ?> 
        </div>
    </div>
    <div class="payment-mobile">
        <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('harbour-payment-block')->toHtml(); ?> 
    </div>
    <div class="grid_9 alpha block-usp-wrap">
        <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('harbour-usp-block')->toHtml(); ?>
    </div>
    
    <div class="clear"></div>
</div>
<script type="text/javascript">
    jQuery(document).ready(function(){
        var myVar = setInterval(function(){ 
            if (jQuery('.top-checkout .amazon-pay-button img').length ){
                jQuery('.top-checkout .amazon-pay-button img').clone().appendTo('.totals-main .amazon-pay-button');
                jQuery('.totals-main .amazon-pay-button img').click(function(){
                    jQuery('.top-checkout .amazon-pay-button img').click();
                });
                myStopFunction();
            }
        }, 1000);

        function myStopFunction() {
            clearInterval(myVar);
        }
    });

    var w = jQuery(window).width();
    var clone = jQuery('.omega.totals-main').clone();
    jQuery('.omega.totals-main').remove();
    if ( w > 767 ){
        clone.insertBefore('.alpha.congift-wrap');
    }else{
        clone.insertAfter('.alpha.congift-wrap');
    }

    jQuery(window).resize(function() {
        var w = jQuery(window).width();
        var clone = jQuery('.omega.totals-main').clone();
        jQuery('.omega.totals-main').remove();
        if ( w > 767 ){
            clone.insertBefore('.alpha.congift-wrap');
        }else{
            clone.insertAfter('.alpha.congift-wrap');
        }
        var myVar = setInterval(function(){ 
            jQuery('.totals-main .amazon-pay-button img').click(function(){
                jQuery('.top-checkout .amazon-pay-button img').click();
            });
            myStopFunction();
        }, 1000);

        function myStopFunction() {
            clearInterval(myVar);
        }
    });
</script>